app:
  title: "Terminfinder Helm Demo"
  locale: "DE-de" # supported: DE-de, EN-en
  addressing: "du" # supported: du, sie
  backend_url: https://terminfinder.opencode.local/api # Public URL to our Backend

replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: selfsigned
  hosts:
    # For this demo, we create a local dns entry (e.g. via /etc/hosts) to try it out with this domain
    # TODO: Change domain for your use-case
    - host: terminfinder.opencode.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cert-terminfinder.opencode.local
      hosts:
        - terminfinder.opencode.local

# For testing, enabled the autoscaling
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
