apiVersion: v2
name: terminfinder-backend-oss
description: Web Backend für die Erstellung von Terminumfragen und die Beantwortung dieser.
type: application
version: 0.0.0
appVersion: "1.0.10"

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.1.2
    condition: postgresql.enabled
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
