{{- $svc := .Values.global.postgresql.service.name | default (printf "%s-postgresql-hl" (include "terminfinder-backend.fullname" .)) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terminfinder-backend.fullname" . }}
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "terminfinder-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "terminfinder-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "terminfinder-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "terminfinder-backend.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_DATABASE
              value: {{ .Values.global.postgresql.auth.database }} 
            - name: DB_PORT
              value: {{ .Values.global.postgresql.service.ports.postgresql | quote }} 
            - name: DB_ADDRESS
              value: {{ printf "%s.%s.svc" $svc .Release.Namespace }}
            - name: DB_USERNAME
              value: {{ .Values.global.postgresql.auth.username }}
            - name: ASPNETCORE_URLS
              value: http://+:8080
            # Secrets:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.postgresql.auth.existingSecret | default (printf "%s-postgresql" (include "common.names.fullname" .)) }}
                  key: {{ .Values.global.postgresql.auth.secretKeys.userPasswordKey | default "password" }}
            # Patches
            - name: Terminfinder__UseHttps
              value: "false"
            - name: Terminfinder__UseCors
              value: "false"
            - name: Terminfinder__Log4NetConfigFilename
              value: log4net.Console.debug.config
            - name: ConnectionStrings__TerminfinderConnection
              value: "Server=$(DB_ADDRESS);Port=$(DB_PORT);Database=$(DB_DATABASE);User ID=$(DB_USERNAME);password=$(DB_PASSWORD);"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /app
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /app
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
