apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-customer-config
data:
  Anrede: {{ .Values.customerConfig.ADDRESSING }}
  Sprache: {{ .Values.customerConfig.LOCALE }}
  Titel: {{ .Values.customerConfig.TITLE }}
  email: {{ .Values.customerConfig.EMAIL }}