loki:
  endpoint: http://loki-gateway.logging-system.svc.cluster.local/loki/api/v1/push
  tenantId: 6703bd86-3601-4ea8-96e4-ecff048f1de9

postgres:
  storageSize: "2Gi"
  pgVersion: "15"
  instances: 3
  enabled: true

traefik:
  enabled: true
