apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "terminfinder-resources.fullname" . }}-stripPrefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
    - /api
