apiVersion: v2
name: terminfinder
description: HelmChart, der das Front- und Backend des Terminfinders kombiniert.
type: application
version: 0.0.3
appVersion: "1.0.10"

dependencies:
  - name: terminfinder-frontend
  - name: terminfinder-backend
  - name: terminfinder-resources
