apiVersion: v2
name: terminfinder
description: HelmChart, der das Front- und Backend des Terminfinders kombiniert.
type: application
version: 0.0.0

dependencies:
  - name: terminfinder-frontend
    version: 0.0.0
  - name: terminfinder-backend
    version: 0.0.0
  - name: terminfinder-resources
    version: 0.0.0
