apiVersion: v2
name: terminfinder-backend
description: Web Backend für die Erstellung von Terminumfragen und die Beantwortung dieser.
type: application
version: 1.0.0
appVersion: "V1.0.9"

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.1.2
    condition: postgresql.enabled
