apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terminfinder-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "terminfinder-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "terminfinder-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "terminfinder-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "terminfinder-backend.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_DATABASE
              value: {{ include "terminfinder-backend.database-name" . }}
            - name: DB_PORT
              value: {{ include "terminfinder-backend.database-port" . }}
            - name: DB_ADDRESS
              value: {{ include "terminfinder-backend.database-server-address" . }}
            - name: DB_USERNAME
              value: {{ include "terminfinder-backend.database-username" . }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "terminfinder-backend.database-existingSecret" . }}
                  key: {{ include "terminfinder-backend.database-userPasswordKey" . }}
            - name: ASPNETCORE_URLS
              value: {{printf "http://+:%d" (int .Values.application.port) }}
            - name: Terminfinder__UseHttps
              value: "false"
            - name: Terminfinder__UseCors
              value: {{ .Values.application.useCors | quote }}
            - name: Terminfinder__Log4NetConfigFilename
              value: log4net.Console.debug.config
            - name: ConnectionStrings__TerminfinderConnection
              value: "Server=$(DB_ADDRESS),$(DB_PORT);Database=$(DB_DATABASE);User ID=$(DB_USERNAME);password=$(DB_PASSWORD);"
          ports:
            - name: http
              containerPort: {{ int .Values.application.port }}
              protocol: TCP
          command:
            - "dotnet"
            - "Dataport.Terminfinder.WebAPI.dll"
            {{- if .Values.application.migrateDB }}
            - "--dbmigrate"
            {{- end }}
          startupProbe:
            failureThreshold: 3
            periodSeconds: 30
            httpGet:
              path: /app
              port: http
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /app
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /app
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
